spring.datasource.url=${POSTGRES_URL:jdbc:postgresql://127.0.0.1:5432/postgres}
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:mysecretpassword}

spring.flyway.validate-migration-naming=true

service.summaries.url=${SUMMARIES_URL:http://localhost:8082}
